name: Validate Lab Structure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check required files
        run: |
          test -f README.md
          test -d infra/ansible
          test -d infra/terraform
          test -d stacks/microstack
          test -d stacks/microceph
          test -d scripts
          test -d docs
          test -d examples
